### PR TITLE
Adjust list view size on small mobile devices.

### PR DESCRIPTION
**Pull request by davealma**
list-view-adjust

### CODE REVIEW

**Comment by davealma** [comment]
@micahwalter This PR should be left for later, until I implement a change needed on next commit!!

**Comment by davealma** [comment]
mobile

**Comment by meghanferrucci** [comment]
@davealma - this looks like the wrong text fields were made smaller here. The only one that needed to be changed from yesterday was the reference number. Ex: 2013.459. See the screenshot for reference.
Screen Shot 2019-03-21 at 2 59 41 PM

**Comment by davealma** [comment]
mobile-list-view

**Pull request merged**
