### PR TITLE
Language routing cleanup

### PR DESCRIPTION
**Pull request by erchaves**
This includes the code from PR https://github.com/mplusmuseum/mplusmuseum-collections-explorer/pull/285. Please merge that in first.

This PR improves the Intl Plugin.
- It now only imports the intl.config.js once, in the server.js file -- and it makes it optional.
- It fixes some lazy cases of returning the whole {...state} in the redux and instead just returns the intl object. We could go even further to break down the intl into specific components. But this is better for now.

### CODE REVIEW

**Comment by davealma** [comment]
@erchaves I see several merge commits, if we can get rid of them to have a cleaner code base by using a new fresh develop branch as base it would be nice.
Also testing on my local I see that redirection is not working, maybe because we need previous PR changes.

**Comment by erchaves** [comment]
@davealma Thanks for calling out those merge issues. I fixed those. Now there is a bug though, so let me close this PR, fix the issues, and then re-open this PR and get back to you.

**Comment by erchaves** [comment]
hey @davealma I fixed the issue I was talking about and now have re-opened this PR for your review thx!

**Comment by erchaves** [comment]
FYI - this is a followup branch to this. But it's still a work-in-progress: https://github.com/mplusmuseum/mplusmuseum-collections-explorer/tree/intl-zh-to-tc

**Comment by davealma** [comment]
I still reproduce the weird issue on navigation, when I click links and buttons to navigate url bar change but page is not changed, I think this is because links are routing to a wrong route. Attaching gif so you can see the behaviour
navigation

**Comment by erchaves** [comment]
To clarify that last comment from David, i think he was on an old commit. So he approved it now.

**Pull request merged**
